Fireburst3d Fffect
GDQuest/godot-visual-effects pull request #8
Opened 2022-02-04 14:39 UTC by Arnklit

- Fix:
- New:
    - Added in Fireburst3d demo
- Update:
    - Added string to csv for demo
- Breaking:

2022-02-04 14:41 UTC, Arnklit commented
ah sorry, didn't realise flames had already merged, I'll rebase this so it can merge.

2022-02-07 12:24 UTC, bramreth requested changes
Absolutely stunning! After style stuff, I had a couple of comments I'd like your thoughts on. Other than that good to merge c:

2022-02-07 12:24 UTC, bramreth commented on godot/FireBurst3D/FireBurst.tscn
> +	vec2 distortion_offset = vec2(sin(x_warp), sin(y_warp)) * warp_strength;
I'm curious as to why both warps go through sin specifically - I'm used to sin and cos for circular motion is there a particular look this achieves?

2022-02-07 12:24 UTC, bramreth commented on godot/FireBurst3D/FireBurst.tscn
> +	gradient_color.rgb *= COLOR.rgb;
```suggestion
	
```
I'm not convinced this helps, the ALPHA already fades out and I wasn't noticing the change in saturation when looking closely

2022-02-07 12:24 UTC, bramreth commented on godot/FireBurst3D/FireBurst.tscn
> +
I was wondering if it was worth making the shader shaded instead and adding EMISSION here?

2022-02-07 12:24 UTC, bramreth commented on godot/FireBurst3D/FireBurst.tscn
> +	float x_warp = animation_progress * warp_speed + UV.y * TAU / warp_scale;
A comment as to why x_warp maps onto UV.y and vice versa would be nice

2022-02-07 12:26 UTC, bramreth commented on godot/FireBurst3D/FireBurst.tscn
> +	vec2 distortion_offset = vec2(sin(x_warp), sin(y_warp)) * warp_strength;
(This is mostly for my curiosity but I'm sure a reader would appreciate a comment too)

2022-02-07 12:28 UTC, Arnklit commented on godot/FireBurst3D/FireBurst.tscn
> +	gradient_color.rgb *= COLOR.rgb;
This currently does nothing, I just added it in case people would want to affect the color of the flames with the gradient in the particle shader, I should probably have commented it.

2022-02-07 12:30 UTC, Arnklit commented on godot/FireBurst3D/FireBurst.tscn
> +	vec2 distortion_offset = vec2(sin(x_warp), sin(y_warp)) * warp_strength;
well we are not actually trying to rotate points, just add wave distortion in both axis. This is supposedly an old trick for how they made the watery warp motion in Quake's water shader

2022-02-07 13:48 UTC, Arnklit commented on godot/FireBurst3D/FireBurst.tscn
> +
I think it just adds unneccessary complexity to make it lit and use emission. Fire is not lit, so there is no reason for it to react to light. Is it because you feel it's clearer if we are assigning values to EMISSION rather than driving albedo values beyond 1.0?

2022-02-07 14:51 UTC, bramreth commented on godot/FireBurst3D/FireBurst.tscn
> +
Ah I didn't see the albedo using HDR :') - although adding the render mode, and setting HDR and a world environment is two-three steps to describe rather than the 1 for setting emission for roughly the same effect - your call just wanted to make sure it was considered if it simplified matters

2022-02-08 13:43 UTC, Arnklit commented on godot/FireBurst3D/FireBurst.tscn
> +	float x_warp = animation_progress * warp_speed + UV.y * TAU / warp_scale;
Good point. Comment added.

2022-02-08 13:44 UTC, Arnklit commented on godot/FireBurst3D/FireBurst.tscn
> +	gradient_color.rgb *= COLOR.rgb;
I ended up removing this as you suggested. It's nice to have the ability to affect this, but since I don't do it here it did feel confusing, even with a comment.

2022-02-08 15:33 UTC, merged